Neos:
  Flow:
    mvc:
      routes:
        'NEOSidekick.Revisions':
          position: 'before Neos.Neos'

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'CodeQ:Revisions':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'NEOSidekick\Revisions\Controller\.*'
