Neos:
  Neos:
    Ui:
      resources:
        javascript:
          NEOSidekick.Revisions:RevisionsView:
            resource: 'resource://NEOSidekick.Revisions/Public/Assets/Plugin.js'
    userInterface:
      translation:
        autoInclude:
          NEOSidekick.Revisions:
            - 'NodeTypes/*'
            - 'Main'
