CodeQ:
  Revisions:
    compression:
      enabled: true # Enables compression of revision xml content in the database
    revisions:
      createRevisionAfterApply: true # Create a revision after applying a revision
