NEOSidekick:
  Revisions:
    enabled: true
    compression:
      enabled: false # Enables compression of revision xml content in the database
    revisions:
      createRevisionAfterApply: true # Create a revision after applying a revision
Neos:
  Neos:
    Ui:
      frontendConfiguration:
        NEOSidekick.Revisions:
          showDeleteButton: false
